# Generated by Django 4.2.1 on 2023-05-25 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experience',
            options={'verbose_name': '체험', 'verbose_name_plural': '체험 관리'},
        ),
        migrations.AlterModelOptions(
            name='perk',
            options={'verbose_name': '특전', 'verbose_name_plural': '특전 관리'},
        ),
    ]
