# Generated by Django 4.2.1 on 2023-05-25 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0002_alter_amenity_description'),
        ('experiences', '0002_alter_experience_options_alter_perk_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('name', models.CharField(max_length=150, verbose_name='목록')),
                ('experiences', models.ManyToManyField(related_name='wishlists', to='experiences.experience', verbose_name='체험')),
                ('rooms', models.ManyToManyField(related_name='wishlists', to='rooms.room', verbose_name='숙소')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='주인')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
