# Generated by Django 4.2.1 on 2023-05-25 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0002_alter_amenity_description'),
        ('experiences', '0002_alter_experience_options_alter_perk_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('file', models.FileField(upload_to='', verbose_name='동영상')),
                ('experience', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='experiences.experience', verbose_name='체험')),
            ],
            options={
                'verbose_name': '동영상',
                'verbose_name_plural': '동영상 관리',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('file', models.ImageField(upload_to='image/', verbose_name='사진')),
                ('description', models.CharField(max_length=150, verbose_name='소개')),
                ('experience', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='experiences.experience', verbose_name='체험')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='rooms.room', verbose_name='숙소')),
            ],
            options={
                'verbose_name': '사진',
                'verbose_name_plural': '사진 관리',
            },
        ),
    ]
