# Generated by Django 4.2.1 on 2023-05-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenity',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='소개'),
        ),
    ]
